# Generated by Django 3.0.5 on 2020-05-23 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register_form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer_Name', models.CharField(max_length=100)),
                ('Date', models.DateField()),
                ('BreakFast', models.CharField(max_length=100)),
                ('Lunch', models.CharField(max_length=100)),
                ('Dinner', models.CharField(max_length=100)),
            ],
        ),
    ]
