# Generated by Django 3.0.5 on 2020-06-03 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_auto_20200529_1740'),
    ]

    operations = [
        migrations.CreateModel(
            name='breakfast_option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Breakfast_List', models.CharField(max_length=100)),
            ],
        ),
    ]
