# Generated by Django 3.0.5 on 2020-06-03 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_breakfast_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_form',
            name='BreakFast',
            field=models.CharField(max_length=50),
        ),
    ]
