# Generated by Django 3.0.5 on 2020-06-03 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0005_auto_20200603_1335'),
    ]

    operations = [
        migrations.DeleteModel(
            name='lunch_option',
        ),
        migrations.AddField(
            model_name='breakfast_option',
            name='Lunch_List',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='register_form',
            name='Customer_Name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='register_form',
            name='Dinner',
            field=models.CharField(blank=True, choices=[('', 'choose....'), ('Dosa', 'Dosa'), ('Parotta', 'Parotta'), ('Chappathi', 'Chappathi'), ('Naan', 'Naan'), ('Fried_Rice', 'Fried_Rice')], max_length=50),
        ),
        migrations.AlterField(
            model_name='register_form',
            name='Lunch',
            field=models.CharField(blank=True, choices=[('', 'choose....'), ('Full_Meals', 'Full_Meals'), ('Veg_Biriyani', 'Veg_Biriyani'), ('Chicken_Biriyani', 'Chicken_Biriyani'), ('Parotta', 'Parotta'), ('Noodles', 'Noodles')], max_length=50),
        ),
    ]
