# Generated by Django 3.0.5 on 2020-06-03 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0006_auto_20200603_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='lunch_option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lunch_List', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='breakfast_option',
            name='Lunch_List',
        ),
        migrations.AlterField(
            model_name='breakfast_option',
            name='Breakfast_List',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='register_form',
            name='BreakFast',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
