# Generated by Django 3.0.5 on 2020-06-03 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0007_auto_20200603_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lunch_option',
            name='Lunch_List',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
