# Generated by Django 3.0.5 on 2020-06-04 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0008_auto_20200603_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='dinner_option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dinner_List', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
