# Generated by Django 3.0.5 on 2020-06-04 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0009_dinner_option'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register_form',
            name='BreakFast',
        ),
        migrations.RemoveField(
            model_name='register_form',
            name='Dinner',
        ),
        migrations.RemoveField(
            model_name='register_form',
            name='Lunch',
        ),
    ]
